-- ============================================================
--  Scrabble Club — schéma Supabase
--  À exécuter dans : Supabase > SQL Editor > New query
-- ============================================================

create table if not exists players (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

create table if not exists games (
  id bigint generated by default as identity primary key,
  played_on date not null,
  session_no int not null,
  game_no int not null,
  top_score int not null,
  notes text,
  created_at timestamptz default now(),
  unique (played_on, session_no, game_no)
);

create table if not exists results (
  id bigint generated by default as identity primary key,
  game_id bigint not null references games(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  score int not null,
  time_seconds int,
  missed_moves int default 0,
  created_at timestamptz default now(),
  unique (game_id, player_id)
);

-- ---- Sécurité : on autorise lecture + écriture publique (club privé) ----
alter table players enable row level security;
alter table games   enable row level security;
alter table results enable row level security;

-- (drop des policies si on relance le script)
drop policy if exists "anon read"   on players;
drop policy if exists "anon write"  on players;
drop policy if exists "anon read"   on games;
drop policy if exists "anon write"  on games;
drop policy if exists "anon read"   on results;
drop policy if exists "anon write"  on results;

create policy "anon read"  on players for select using (true);
create policy "anon write" on players for all    using (true) with check (true);
create policy "anon read"  on games   for select using (true);
create policy "anon write" on games   for all    using (true) with check (true);
create policy "anon read"  on results for select using (true);
create policy "anon write" on results for all    using (true) with check (true);
