-- ============================================================
--  Migration auth (Phase A)
--  À exécuter dans Supabase SQL Editor.
-- ============================================================

-- 1) Étendre la table players pour lier auth.users + email
alter table players add column if not exists auth_user_id uuid references auth.users(id) on delete set null;
alter table players add column if not exists email text;

create unique index if not exists idx_players_auth_user_id
  on players(auth_user_id) where auth_user_id is not null;
create unique index if not exists idx_players_email
  on players(lower(email)) where email is not null;

-- 2) Historique des parties d'entraînement (pour la page Parties)
create table if not exists training_games (
  id bigint generated by default as identity primary key,
  player_id bigint not null references players(id) on delete cascade,
  mode text not null,
  with_joker boolean not null default false,
  time_per_move int not null default 0,
  total_score int not null,
  sum_neg int not null,
  total_time_seconds int,
  history jsonb,                       -- détail coup par coup pour Revoir
  created_at timestamptz default now()
);

create index if not exists idx_training_games_player_date
  on training_games(player_id, created_at desc);

alter table training_games enable row level security;
drop policy if exists "anon read" on training_games;
drop policy if exists "anon write" on training_games;
create policy "anon read"  on training_games for select using (true);
create policy "anon write" on training_games for all using (true) with check (true);
