-- ============================================================
--  Migration tournois + club (Phase E)
--  À exécuter dans Supabase SQL Editor.
-- ============================================================

-- 1) Club du joueur
alter table players add column if not exists club text;

-- 2) Tournois (regroupent plusieurs parties pré-tirées)
create table if not exists tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by_player_id bigint references players(id),
  created_at timestamptz default now()
);

create index if not exists idx_tournaments_created on tournaments(created_at desc);

-- 3) Lien parties → tournoi (nullable pour les parties existantes)
alter table prepared_games add column if not exists tournament_id
  bigint references tournaments(id) on delete cascade;

create index if not exists idx_prepared_games_tournament on prepared_games(tournament_id);

-- 4) RLS
alter table tournaments enable row level security;
drop policy if exists "anon read"  on tournaments;
drop policy if exists "anon write" on tournaments;
create policy "anon read"  on tournaments for select using (true);
create policy "anon write" on tournaments for all    using (true) with check (true);
