-- ============================================================
--  Partie pré-tirée (Phase 2)
--  À exécuter dans Supabase SQL Editor.
-- ============================================================

create table if not exists prepared_games (
  id bigint generated by default as identity primary key,
  name text not null,
  mode text not null default 'duplicate',  -- duplicate | 7sur8 | 7et8 | 789
  with_joker boolean not null default false,
  time_per_move int not null default 0,    -- 0 = illimité
  dictionary text not null default 'ODS9',
  -- Séquence complète : [{rack: "ABCDEFG", top: {word, row, col, dir, blanks, score}}, ...]
  moves jsonb not null,
  total_top_score int not null default 0,
  created_by_player_id bigint references players(id),
  created_at timestamptz default now()
);

create index if not exists idx_prepared_games_created on prepared_games(created_at desc);

-- Résultat d'un joueur sur une partie pré-tirée
create table if not exists prepared_game_results (
  id bigint generated by default as identity primary key,
  prepared_game_id bigint not null references prepared_games(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  total_score int not null,
  sum_neg int not null,
  total_time_seconds int,
  -- Détail coup par coup pour la feuille de route
  details jsonb,
  finished_at timestamptz default now(),
  unique (prepared_game_id, player_id)
);

-- RLS publiques (cohérent avec le reste)
alter table prepared_games enable row level security;
alter table prepared_game_results enable row level security;

drop policy if exists "anon read" on prepared_games;
drop policy if exists "anon write" on prepared_games;
drop policy if exists "anon read" on prepared_game_results;
drop policy if exists "anon write" on prepared_game_results;

create policy "anon read"  on prepared_games for select using (true);
create policy "anon write" on prepared_games for all using (true) with check (true);
create policy "anon read"  on prepared_game_results for select using (true);
create policy "anon write" on prepared_game_results for all using (true) with check (true);
